dns:
  resolvers:
    - 8.8.4.4
    - 8.8.8.8

sources:
  - name: oisd-small
    category: adblock
    format: rpz
    url: https://small.oisd.nl/rpz
  - name: frellwits-swedish-hosts
    category: adblock
    format: hosts
    url: https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
  - name: firebog-adguard-dns
    category: adblock
    format: domains
    url: https://v.firebog.net/hosts/AdguardDNS.txt
  - name: hagezi-popup-ads
    category: adblock
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads-onlydomains.txt
  - name: custom-adblock
    category: adblock
    format: domains
    path: custom/adblock.txt

  - name: firebog-easyprivacy
    category: privacy
    format: domains
    url: https://v.firebog.net/hosts/Easyprivacy.txt
  - name: hagezi-amazon
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.amazon-onlydomains.txt
  - name: hagezi-apple
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.apple-onlydomains.txt
  - name: hagezi-huawei
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.huawei-onlydomains.txt
  - name: hagezi-windows-office
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice-onlydomains.txt
  - name: hagezi-tiktok-aggressive
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok.extended-onlydomains.txt
  - name: hagezi-lg-webos
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.lgwebos-onlydomains.txt
  - name: hagezi-vivo
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.vivo-onlydomains.txt
  - name: hagezi-oppo-realme
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.oppo-realme-onlydomains.txt
  - name: hagezi-xiaomi
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.xiaomi-onlydomains.txt
  - name: hagezi-samsung
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.samsung-onlydomains.txt
  - name: hagezi-roku
    category: privacy
    format: domains
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.roku-onlydomains.txt
  - name: custom-privacy
    category: privacy
    format: domains
    path: custom/privacy.txt
