dns:
  resolvers:
    - 1.0.0.1
    - 1.1.1.1

public_suffix_list: https://raw.githubusercontent.com/publicsuffix/list/refs/heads/main/public_suffix_list.dat

allowlist:
  - custom/allowlist.txt

sources:
  rpz:
    - https://small.oisd.nl/rpz
  adblock:
    - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    - https://easylist.to/easylist/easyprivacy.txt
  hosts:
    - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
    - https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/gambling/hosts
    - https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/hosts
  domains:
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.amazon-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.apple-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.huawei-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok.extended-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.lgwebos-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.vivo-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.oppo-realme-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.xiaomi-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.samsung-onlydomains.txt
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.roku-onlydomains.txt
    - custom/adblock.txt
    - custom/privacy.txt
